name: tmdb-meili

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Get TMDB Movie ID Export
        run: |
         DATE=$(date +"%m_%d_%Y")
         wget -O tmdb_export.json.gz https://files.tmdb.org/p/exports/movie_ids_${DATE}.json.gz
         gunzip tmdb_export.json.gz
         ls
         mv movie_ids_${DATE}.json movie_ids.json

